### PR TITLE
Add support for changing the gem's working directory

### PR DESCRIPTION
**Pull request by juanibiapina**
This should allow gems which are not in the repository root.

### CODE REVIEW

**Comment by juanibiapina** [comment]
This gives: `Unexpected value 'defaults'`

**Comment by juanibiapina** [comment]
I fixed it by overriding the working directory in each step.

Reference: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsstepsworking-directory

**Review by jansiwy — COMMENTED** [review]
Can you please add CHANGELOG.md file?

Apart from that: LGTM!

**Comment by juanibiapina** [comment]
I created the CHANGELOG with version `1.1.0`. According to github actions versioning recommendations we should push a corresponding tag (`v1.1.0`) and force push `v1` to point to the same commit. I guess I can't do that from here.

**Review by jansiwy — APPROVED** [review]

**Pull request merged**
